- name: loops
  hosts: localhost
  become: yes
  tasks:
  - name: print person
    ansible.builtin.debug:
      name: "{{item}}"
      state: present # item is a default keyword
    loop:
    - git
    - mysql
    - postfix
    